### ISSUE TITLE
Can't achieve more than 92% precision

### ISSUE THREAD

**Issue by eriksonssilva** [GuitarML/SmartAmpPro#24]
Hello there! Thanks for this amazing tool. It's certainly ground breaking!
I have done all I could, followed the instructions and ignored them, but I could not achieve a 99% precision like on your demo video.
I am approaching it slightly differently though: I'm recording monitoring trough a VST, then I'll use The processed Signal 100% to one side and the DI to the other.
Maximum I could get was 92% (which is impressive already), but it lacks a lot of the bottom end, it sounds a bit thinner...
Any ideas on what could I try differently?
Thanks a lot in advance!

**Comment by GuitarML** [comment]
@eriksonssilva Thanks for reaching out! Are you capturing some kind of amp modelling vst? 

SmartAmpPro's capture is very fast at the cost of accuracy. It's likely that 92% is the best it can do for the particular sound. Also, I've learned since making that video that the 99% accuracy I was getting is misleading, as it is using "Validation" training accuracy (audio it's already learned from) as opposed to "Test" accuracy (audio it's never seen before).  Also, for whatever reason, the TS9's sound seems to do extremely well with whatever machine learning I throw at it. 

If you want better accuracy, the machine learning code I've been using most recently is: https://github.com/GuitarML/Automated-GuitarAmpModelling
You will be able to get much higher accuracy with this code, but it takes longer (about 45 minutes) and it's separate from the plugin that runs the models [NeuralPi](https://github.com/GuitarML/NeuralPi).  Still, in a 1 to 1 comparison I've noticed slight variation in the bottom end for most of these models. I've seen other people use a post EQ effect to make up the difference.

Hope that helps!

**Comment by eriksonssilva** [comment]
Thanks a lot for the answer! I really appreciate!
But I did not understand one thing.
do I have to use that with NeuralPi? Or can I train it and use on the VST normally?
and regarding the NeuralPi, which one can I use ? Is the 3 enough?
Thanks!

**Comment by GuitarML** [comment]
The NeuralPi software can be used as a normal VST on Windows and Mac. The Elk OS version requires the raspberry pi hardware. Use the latest release version (currently 1.3), which is the version linked on GuitarML.com.  The models trained with Automated-GuitarAmpModelling will not be compatible with SmartAmpPro.  Does that answer your questions?

**Comment by eriksonssilva** [comment]
Ah, got it! I thought that NeuralPi worked on Raspberry pi only!
That answers it, yes!
But I think I wasn't clear on the Pi question.
Which Raspberry Pi board do I need in order to use it? And do you know if I would be able using other effects such as delay/eq and etc on the pi?
Thanks! (You can close this one if you wish!)

**Comment by GuitarML** [comment]
@eriksonssilva You would need a Raspberry Pi 4 (4GB version works fine) and the HiFiBerry DAC + ADC hat. Full instructions are here: https://towardsdatascience.com/neural-networks-for-real-time-audio-raspberry-pi-guitar-pedal-bded4b6b7f31

The latest NeuralPi software has basic EQ/Delay/Reverb built in.  It uses Elk OS, which is capable of running VST plugins, given that you have the source code and can compile them for Elk OS. And there are other guitar effects projects out there that you can build on the Raspberry Pi. The sky is the limit really, if you want to run some kind of effect on the Pi then there's probably a way to do it, it just depends how involved you want to get. 

Happy to help! Closing this issue
